[package]
name = "mlm_parse"
version = "0.1.0"
edition = "2024"

[dependencies]
ammonia = { version = "4.1" }
anyhow = "1.0.100"
htmlentity = "1.3.2"
once_cell = "1.21.3"
maplit = { version = "1" }
regex = "1.12.2"
unidecode = "0.3.0"
